```{r}
library(readxl)
df <- read_excel("/Users/sharedvis/Downloads/Total Penumpang Pelayaran dalam Negeri di Pelabuhan Utama.xlsx")
```

```{r}
library("forecast")
library("graphics")
library("TTR")
library("TSA")
```

```{r}
df.ts <- ts(df$jumlah)
summary(df.ts)
```
```{r}
training_ma <- df[1:85,]
testing_ma <- df[86:109,]
train_ma.ts <- ts(training_ma$jumlah)
test_ma.ts <- ts(testing_ma$jumlah)
```

```{r}
plot(df.ts, col="red",main="Plot semua data")
points(df.ts)
```


```{r}
plot(train_ma.ts, col="blue",main="Plot data latih")
points(train_ma.ts)
```


```{r}
plot(test_ma.ts, col="blue",main="Plot data uji")
points(test_ma.ts)
```

```{r}
data.sma<-SMA(train_ma.ts, n=4)
data.sma
```

```{r}
data.ramal<-c(NA,data.sma)
data.ramal
```


```{r}
data.gab<-cbind(aktual=c(train_ma.ts,rep(NA,109)),pemulusan=c(data.sma,rep(NA,109)),ramalan=c(data.ramal,rep(data.ramal[length(data.ramal)],108)))
data.gab 
```

Adapun plot data deret waktu dari hasil peramalan yang dilakukan adalah sebagai berikut.

```{r}
ts.plot(df.ts, xlab="Time Period ", ylab="jumlah")
points(df.ts)
lines(data.gab[,2],col="green",lwd=2)
lines(data.gab[,3],col="red",lwd=2)
legend("topleft",c("data aktual","data pemulusan","data peramalan"), lty=8, col=c("black","green","red"), cex=0.5)
```


```{r}
error_train.sma = train_ma.ts-data.ramal[1:length(train_ma.ts)]
SSE_train.sma = sum(error_train.sma[5:length(train_ma.ts)]^2)
MSE_train.sma = mean(error_train.sma[5:length(train_ma.ts)]^2)
MAPE_train.sma = mean(abs((error_train.sma[5:length(train_ma.ts)]/train_ma.ts[5:length(train_ma.ts)])*100))

akurasi_train.sma <- matrix(c(SSE_train.sma, MSE_train.sma, MAPE_train.sma))
row.names(akurasi_train.sma)<- c("SSE", "MSE", "MAPE")
colnames(akurasi_train.sma) <- c("Akurasi m = 4")
akurasi_train.sma
```


```{r}
#Menghitung nilai keakuratan data uji
error_test.sma = test_ma.ts-data.gab[97:120,3]
SSE_test.sma = sum(error_test.sma^2)
MSE_test.sma = mean(error_test.sma^2)
MAPE_test.sma = mean(abs((error_test.sma/test_ma.ts*100)))

akurasi_test.sma <- matrix(c(SSE_test.sma, MSE_test.sma, MAPE_test.sma))
row.names(akurasi_test.sma)<- c("SSE", "MSE", "MAPE")
colnames(akurasi_test.sma) <- c("Akurasi m = 4")
akurasi_test.sma
```

